<a href="https://colab.research.google.com/github/gabrielvieiraf/ProjetosPython/blob/master/GoogleColab/Calculo/Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matemática: Operações com Matrizes

Matrizes são estruturas tabelas com linhas e colunas muito ultilizadas na matemática.

Uma matriz em Python pode ser representada como uma lista de listas.

##  Soma de matrizes

**Exemplo 01**

Uma determinada empreiteira quer saber qual funcionário realizou o maior numero de trabalho por $ m² $.

Para isso, o supervisor anotou os dados de trÊs dos melhores funcionários, em duas obras distintas. Encontre o resultado final de todos os dias trabalhados para descobrir o funcionário mais produtivo.

### Importando dados do Google Drive

In [1]:
import pandas as pd

# Permite Importar dados do Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Caminho para dados do arquivo csv 
csv01 = '/content/drive/My Drive/Colab Notebooks/Alura/Colaboradores01.csv'
obra01 = pd.read_csv(csv01)
obra01.rename(columns= {'Unnamed: 0':'Colaboradores'}, inplace=True)

print('\nObra 01')
display(obra01)

print()

print('Obra 02')
# Caminho para dados do arquivo csv 
csv02 = '/content/drive/My Drive/Colab Notebooks/Alura/Colaboradores02.csv'
obra02 = pd.read_csv(csv02)

obra02.rename(columns= {'Unnamed: 0':'Colaboradores'}, inplace=True)
display(obra02)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Obra 01


Colaboradores  Dia1  Dia2  Dia3  Dia4  Dia5
0  Colaborador(a) 1    12     5    10     7     4
1  Colaborador(a) 2     4     7     6     8     8
2  Colaborador(a) 3     7    12    13    10     5


Obra 02


Colaboradores  Dia1  Dia2  Dia3  Dia4  Dia5
0  Colaborador(a) 1    12    14    15    16    12
1  Colaborador(a) 2     7    14    17     8     7
2  Colaborador(a) 3     4     5     8     6     6

### Transformando DataFrame em matriz para soma

In [2]:
import numpy as np

# Transformando Dataframe em Matriz
del obra01['Colaboradores']

matriz_A = np.array(obra01)
display(matriz_A)
print()

del obra02['Colaboradores']

matriz_B = np.array(obra02)
display(matriz_B)
print()

matriz_C = matriz_A + matriz_B
display(matriz_C)

array([[12,  5, 10,  7,  4],
       [ 4,  7,  6,  8,  8],
       [ 7, 12, 13, 10,  5]])

array([[12, 14, 15, 16, 12],
       [ 7, 14, 17,  8,  7],
       [ 4,  5,  8,  6,  6]])

array([[24, 19, 25, 23, 16],
       [11, 21, 23, 16, 15],
       [11, 17, 21, 16, 11]])

### Encontrando funcionário mais produtivo

In [3]:
colaborador_01 = sum(matriz_C[0])
colaborador_02 = sum(matriz_C[1])
colaborador_03 = sum(matriz_C[2])

colaboradores = {'Colaborador 01': colaborador_01,
                 'Colaborador 02': colaborador_02,
                 'Colaborador 03': colaborador_03}

resultado = pd.DataFrame(list(colaboradores.items()),columns = ['Colaboradores','m2'])
resultado

Colaboradores   m2
0  Colaborador 01  107
1  Colaborador 02   86
2  Colaborador 03   76

## Subtração de Matrizes

**Exemplo 02**

O coordenador de qualidade de uma empresa de cursos de capacitação quer descobrir quais cursos de sua plataforma estão com menos procura e quais os turnos menos procurados.

### Importando Dados do Google Drive

In [4]:
# Caminho para dados do arquivo csv 
csv03 = '/content/drive/My Drive/Colab Notebooks/Alura/cursos01.csv'
cursos01 = pd.read_csv(csv03)

print('\nCursos 01')
display(cursos01)

print()

print('Cursos 02')
# Caminho para dados do arquivo csv 
csv04 = '/content/drive/My Drive/Colab Notebooks/Alura/cursos02.csv'
cursos02 = pd.read_csv(csv04)


display(cursos02)


Cursos 01


turno  tec_eletronica  tec_eletrotecnica  tec_informatica
0  manha              35                 38               30
1  tarde              28                 35               35
2  noite              40                 33               30


Cursos 02


turno  tec_eletronica  tec_eletrotecnica  tec_informatica
0  manha              23                 20               17
1  tarde              22                 23               18
2  noite              17                 22               20

### Transformando DataFrame em matriz para subtração

In [5]:
del cursos01['turno']
matriz_D = np.array(cursos01)

del cursos02['turno']
matriz_E = np.array(cursos02)

matriz_F = matriz_D - matriz_E

display(matriz_F)

array([[12, 18, 13],
       [ 6, 12, 17],
       [23, 11, 10]])

### Encontrando Turno e cursos com menos alunos

In [6]:
resultado = pd.DataFrame(matriz_F)
display(resultado[0])

eletronica = sum(resultado[0])
eletrotecnica = sum(resultado[1])
informatica = sum(resultado[2])

cursos = {'Eletrônica': eletronica,
          'Eletrotécnica': eletrotecnica,
          'Informática': informatica}

resultado = pd.DataFrame(list(cursos.items()),columns = ['Cursos','n_alunos'])
display(resultado)

print()

manha = sum(matriz_F[0])
tarde = sum(matriz_F[1])
noite = sum(matriz_F[2])

turnos = {'Manhã': manha,
          'Tarde': tarde,
          'Noite': noite}

resultado = pd.DataFrame(list(turnos.items()),columns = ['Turnos','n_alunos'])
resultado

0    12
1     6
2    23
Name: 0, dtype: int64

Cursos  n_alunos
0     Eletrônica        41
1  Eletrotécnica        41
2    Informática        40

Turnos  n_alunos
0  Manhã        43
1  Tarde        35
2  Noite        44

## Multiplicação de Matrizes por um Número

**Exemplo 03**

Uma empresa de painéis solares deseja saber quanto está sendo pago aos colaboradores no mês de Julho, sabendo que 8% da venda dos projetos é dado aos colaboradores. 

O departamento de vendas elaborou uma tabela para conseguir apurar essa informação, contendo todos os dados necessários.



In [7]:
matriz_J = np.array([[2500,3000,4700],[28000,31000,42000]])
display(matriz_J)

# 8% da venda
contribuicao = 0.08

matriz_H = contribuicao * matriz_J

print()

display(matriz_H)

array([[ 2500,  3000,  4700],
       [28000, 31000, 42000]])

array([[ 200.,  240.,  376.],
       [2240., 2480., 3360.]])

In [8]:
vendas_julho = pd.DataFrame(matriz_H, columns = ['Vendedor 1','Vendedor 2','Vendedor 3'], index=['Projeto','Sistemas'])
vendas_julho

Vendedor 1  Vendedor 2  Vendedor 3
Projeto        200.0       240.0       376.0
Sistemas      2240.0      2480.0      3360.0

In [9]:
soma = vendas_julho.sum(axis=0)
soma

Vendedor 1    2440.0
Vendedor 2    2720.0
Vendedor 3    3736.0
dtype: float64

In [10]:
vendas_julho = pd.DataFrame(soma, columns = ['Quantia em R$'])
vendas_julho

Quantia em R$
Vendedor 1         2440.0
Vendedor 2         2720.0
Vendedor 3         3736.0

## Multiplicação de Matrizes

**Exemplo 04**

A gerente financeira de obras de uma determinada organização, está com duas obras em andamento, e ela precisa comprar materiais para essas duas obras.

A gerente quer fazer a cotação de preço entre os fornecedores, pois a empresa costuma comprar materiais apenas de um fornecedor por vez para facilitar as questões fiscais. 

Você está encarregado de encontrar o melhor fornecedor entre as cotações que a gerente financeira conseguiu.



### **Dados:**

## **Obra 01**


*   25 kg de areia
*   20 kg de pedra
*   30 kg de cimento
*   32 kg de impermeabilizante

## **Obra 2**

*   28 kg de areia
*   24 kg de pedra
*   35 kg de cimento
*   38 kg de impermeabilizante

### Importando tabela de fornecedores do Google Drive

In [11]:
# Caminho para dados do arquivo csv 
csv05 = '/content/drive/My Drive/Colab Notebooks/Alura/valores.csv'
fornecedores = pd.read_csv(csv05)

display(fornecedores)


produto(1kg)  fornecedor 1   fornecedor 2
0              Areia          0.20            0.2
1              Pedra          4.00            3.4
2            Cimento          0.40            0.6
3  Impermeabilizante         12.96           11.2

### Criando Matrizes das Obras

Para uma melhor visualização dos dados enquanto trabalhamos com matriz, podemos usar a matriz transposta.

In [64]:
matriz_I = np.transpose(np.array([[25,20,30,32],[28,24,35,38]]))
matriz_N = np.transpose(np.array([[28,24,35,38],[25,20,30,32]]))

obras = pd.DataFrame(matriz_I, columns= ['Obra 01 (kg)', 'Obra 02 (kg)'])
obras['Materiais'] = ['Areia','Pedra','Cimento','Impermeabilizante']

# Reordenando Dataframe
obras = obras[['Materiais','Obra 01 (kg)', 'Obra 02 (kg)']]
display(obras)

print('\n Matriz_I transposta:\n')
df = pd.DataFrame(matriz_I)
display(df)

print('\n Matriz_I:\n')
df = pd.DataFrame(np.array([[25,20,30,32],[28,24,35,38]]))
display(df)

Materiais  Obra 01 (kg)  Obra 02 (kg)
0              Areia            25            28
1              Pedra            20            24
2            Cimento            30            35
3  Impermeabilizante            32            38


 Matriz_I transposta:



0   1
0  25  28
1  20  24
2  30  35
3  32  38


 Matriz_I:



0   1   2   3
0  25  20  30  32
1  28  24  35  38

In [69]:
try:
  del obras['Materiais']
  del fornecedores['produto(1kg)']
except:
  print('Coluna já excluida, prosseguindo...\n')

matriz_M = np.array(fornecedores)

# Multiplicando matrizes 

matriz_L = np.multiply(matriz_M,matriz_I )
matriz_O = np.multiply(matriz_M,matriz_N )

# Criando visualização dos resultados

print('Matriz_L')
df = pd.DataFrame(matriz_L)
display(df)


print('\n\nMatriz_O')
df = pd.DataFrame(matriz_O)
display(df)

# Somando preços das obras 1 e 2
preco = matriz_L.sum(axis=0) + matriz_O.sum(axis=0)

# Criando DataFreme final para a conclusão do problema
print('\n\ndf final')
preco_df = pd.DataFrame(preco, index= ['Fornecedo 01','Fornecedor 02'], columns =['Preço em (R$)'])
preco_df


Coluna já excluida, prosseguindo...

Matriz_L


0      1
0    5.00    5.6
1   80.00   81.6
2   12.00   21.0
3  414.72  425.6



Matriz_O


0      1
0    5.60    5.0
1   96.00   68.0
2   14.00   18.0
3  492.48  358.4



df final


Preço em (R$)
Fornecedo 01          1119.8
Fornecedor 02          983.2